### ISSUE TITLE
Setup doesn't work 

### ISSUE THREAD

**Issue by syagawa** [Norio4/rust_actixweb_boilerplate#1]
READMEのSetupにしたがって下記のコマンドを叩きましたが、`cargo +stable install cargo-edit`で"error: failed to run custom build command for `openssl-sys v0.9.66`"というエラーが出ます。

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
sudo snap install rustup --classic
rustup update stable
rustup component add rls rust-analysis rust-src
cargo +stable install cargo-edit
```
なおREADMEのSetupのコマンドだけではうまくいかなったためオプションを追加したりコマンドを追加したりしています。

環境はLinux/Ubuntu 20.04.3 LTS (Focal Fossa)です。

**Comment by Norio4** [comment]
Ubuntuの場合、libssl-devが無いまたは古い可能性があります。

上から順番に実行してみてください。
その後、再度cargo installが動作するか試してみてください。
```
    apt-get update -y
    apt-get install -y libssl-dev
    apt-get install -y pkg-config
```

また、rustupはcurl経由で設定済みなので下記コマンドは不要です。

```sudo snap install rustup --classic```

curl実行後に下記を実行することでrustupは使えるようになるかと思います。

```. "$HOME/.cargo/env"```

**Comment by syagawa** [comment]
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ . "$HOME/.cargo/env"
$ rustup component add rls rust-analysis rust-src
$ sudo apt install libpq-dev -y
$ apt install libssl-dev
$ apt install pkg-config
$ cargo install diesel_cli --no-default-features --features postgres
$ diesel setup
$ cargo run

上記のコマンドでcargo run まで行きましたがcargo run が下記のエラーで停止します。

```
Compiling rust_actixweb_boilerplate v0.1.0 (/home/playground/rust_actixweb_boilerplate)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 57s
     Running `target/debug/rust_actixweb_boilerplate`
thread 'main' panicked at 'DATABASE_URL must be set: NotPresent', src/main.rs:46:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.

```

**Comment by Norio4** [comment]
.envに関する記述が足りていませんでした。
PostgreSQLが必要になります。

**Comment by Norio4** [comment]
Setupを更新しました。
